description: >-
  Jekflix is a template for Jekyll inspired by Netflix and made by Thiago
  Rossener.
tags:
  - null
  - null
  - null
  - null
  - null
show_hero: false
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - url: /contact
  - title: Feed
    url: /feed.xml
