description: >-
  Jekflix is a template for Jekyll inspired by Netflix and made by Thiago
  Rossener.
tags:
  - null
  - null
  - null
  - theme
  - netlify
show_hero: false
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: youremail@test.com
disqus_username: disqus_username
